"""empty message

Revision ID: a3331f358792
Revises: b70ac7616576
Create Date: 2024-12-08 15:20:49.816039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3331f358792'
down_revision = 'b70ac7616576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='paymentstatus'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
